[package]
name = "dr_spec"
authors = ["levaleureux"]
version = "0.1.0"
homepage = "https://github.com/levaleureux/dr_spec"
keywords = ['dragonruby', 'rspec']

# Optional:
# documentation = "https://example.com"
repository = "https://github.com/levaleureux/dr_spec"

# Which files do you want to be automatically required from your package.
requires = []

[package.installs]
# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "5.9"
edition = "standard"
